version: '2'
services:
 web:
  build: .
  command: bundle exec rails s -p 4004 -b '0.0.0.0' 
  ports:
   - "4004:4004"
  depends_on:
   - db
 db:
  image: postgres
  volumes:
   - ./tmp/db:/var/lib/postgresql/data
